const { useDB } = require("./connect");
const fs = require("fs");
require("dotenv").config();

const teamMap = {
  3: "Arsenal",
  7: "Aston_Villa",
  91: "Bournemouth",
  36: "Brighton",
  90: "Burnley",
  8: "Chelsea",
  31: "Crystal_Palace",
  11: "Everton",
  13: "Leicester",
  14: "Liverpool",
  43: "Man_City",
  1: "Man_Utd",
  4: "Newcastle",
  45: "Norwich",
  49: "Sheffield_Utd",
  20: "Southampton",
  6: "Spurs",
  57: "Watford",
  21: "West_Ham",
  39: "Wolves",
};

const getLatestElementsAndWriteToFile = async (client) => {
  const allData = await client
    .db("fpl")
    .collection("latestElements")
    .find({})
    .project({
      // _id: 0,
      // assists: 0,
      // bonus: 0,
      // bps: 0,
      // chance_of_playing_next_round: 0,
      // chance_of_playing_this_round: 0,
      // clean_sheets: 0,
      // code: 0,
      // corners_and_indirect_freekicks_order: 0,
      // corners_and_indirect_freekicks_text: 0,
      // cost_change_event: 0,
      // cost_change_event_fall: 0,
      // cost_change_start: 0,
      // cost_change_start_fall: 0,
      // creativity: 0,
      // creativity_rank: 0,
      // creativity_rank_type: 0,
      // direct_freekicks_order: 0,
      // direct_freekicks_text: 0,
      // dreamteam_count: 0,
      element_type: 1,
      // ep_next: 0,
      // ep_this: 0,
      // event_points: 0,
      first_name: 1,
      form: 1,
      // goals_conceded: 0,
      // goals_scored: 0,
      // ict_index: 0,
      // ict_index_rank: 0,
      // ict_index_rank_type: 0,
      id: 1,
      // in_dreamteam: 0,
      // influence: 0,
      // influence_rank: 0,
      // influence_rank_type: 0,
      minutes: 1,
      // news: 0,
      // news_added: 0,
      now_cost: 1,
      // own_goals: 0,
      // penalties_missed: 0,
      // penalties_order: 0,
      // penalties_saved: 0,
      // penalties_text: 0,
      // photo: 0,
      // points_per_game: 0,
      // red_cards: 0,
      // saves: 0,
      second_name: 1,
      // selected_by_percent: 0,
      // special: 0,
      // squad_number: 0,
      // status: 0,
      team: 1,
      team_code: 1,
      // threat: 0,
      // threat_rank: 0,
      // threat_rank_type: 0,
      total_points: 1,
      // transfers_in: 0,
      // transfers_in_event: 0,
      // transfers_out: 0,
      // transfers_out_event: 0,
      value_form: 1,
      value_season: 1,
      web_name: 1,
      // yellow_cards: 0,
      // gw_element: 0,
      // gw_fixture: 0,
      // gw_opponent_team: 0,
      gw_total_points: 1,
      // gw_was_home: 0,
      // gw_kickoff_time: 0,
      // gw_team_h_score: 0,
      // gw_team_a_score: 0,
      // gw_round: 0,
      gw_minutes: 1,
      // gw_goals_scored: 0,
      // gw_assists: 0,
      // gw_clean_sheets: 0,
      // gw_goals_conceded: 0,
      // gw_own_goals: 0,
      // gw_penalties_saved: 0,
      // gw_penalties_missed: 0,
      // gw_yellow_cards: 0,
      // gw_red_cards: 0,
      // gw_saves: 0,
      // gw_bonus: 0,
      // gw_bps: 0,
      // gw_influence: 0,
      // gw_creativity: 0,
      // gw_threat: 0,
      // gw_ict_index: 0,
      // gw_value: 0,
      // gw_transfers_balance: 0,
      // gw_selected: 0,
      // gw_transfers_in: 0,
      // gw_transfers_out: 0,
      points_pr_mill: 1,
      points_pr_game_pr_mill: 1,
      ownPercent: 1,
      capPercent: 1,
      ownPercentMinus1gw: 1,
      capPercentMinus1gw: 1,
      ownPercentMinus2gw: 1,
      capPercentMinus2gw: 1,
      ownPercentMinus3gw: 1,
      capPercentMinus3gw: 1,
      ownPercentMinus4gw: 1,
      capPercentMinus4gw: 1,
      last5ppg: 1,
      last5ppgpm: 1,
      team_code: 1,
    })

    .toArray();
  allData.forEach((el) => (el.team_written = teamMap[el.team_code]));
  // console.log(Object.keys(allData[0]));
  fs.writeFileSync("latestElements.json", JSON.stringify(allData));
};

useDB(getLatestElementsAndWriteToFile);
